const eos = [
    { eo: "14147", title: "Initial Rescissions of Harmful Executive Orders", summary: "Revokes 78 Biden EOs—DEI, borders, climate", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 5, impact_level: "High", last_updated: "1/20/25" },
    { eo: "14148", title: "Protecting the American People Against Invasion", summary: "Ends catch-and-release, reinstates Remain in Mexico", bill_status: "No bill yet", bill_link: null, court_challenges: "Lawsuit filed—ACLU, 4/6/25", court_link: "https://x.com/search?q=ACLU%20lawsuit%20EO%2014148", risk_level: 9, impact_level: "High", last_updated: "4/7/25" },
    { eo: "14149", title: "Restoring Freedom of Speech and Ending Federal Censorship", summary: "Bars feds from censoring online speech", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 5, impact_level: "High", last_updated: "1/20/25" },
    { eo: "14150", title: "Declaring a National Energy Emergency", summary: "Fast-tracks fossil fuel permits", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 5, impact_level: "High", last_updated: "1/20/25" },
    { eo: "14151", title: "Establishing the Dept of Government Efficiency", summary: "Creates DOGE to cut fed spending", bill_status: "Intent declared by Rep. Y, 4/4/25", bill_link: null, court_challenges: "Lawsuit filed—19 states", court_link: "https://x.com/search?q=unions%20lawsuit%20EO%2014151", risk_level: 6, impact_level: "Medium", last_updated: "4/4/25" },
    { eo: "14152", title: "Reinstating the 1776 Commission", summary: "Revives patriotic education push", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 4, impact_level: "Medium", last_updated: "1/20/25" },
    { eo: "14153", title: "Protecting American Jobs Against Foreign Adversaries", summary: "Bans China from fed contracts", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 5, impact_level: "High", last_updated: "1/20/25" },
    { eo: "14154", title: "Ending Federal Overreach in Education", summary: "Cuts Dept of Ed rules, boosts states", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 5, impact_level: "High", last_updated: "1/20/25" },
    { eo: "14155", title: "Securing American Elections", summary: "Mandates voter ID, paper ballots for fed elections", bill_status: "H.R. 22, Sponsored by Rep. X", bill_link: "https://www.congress.gov/bill/119th-congress/house-bill/22", court_challenges: "Lawsuit threatened—NAACP", court_link: "https://x.com/search?q=NAACP%20lawsuit%20EO%2014155", risk_level: 5, impact_level: "High", last_updated: "4/7/25" },
    { eo: "14156", title: "Enhancing National Defense Through Military Modernization", summary: "Boosts military tech funding", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 4, impact_level: "Medium", last_updated: "1/20/25" },
    { eo: "14157", title: "Promoting American Manufacturing", summary: "Incentives for US-made goods", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 4, impact_level: "Medium", last_updated: "1/21/25" },
    { eo: "14158", title: "Terminating Federal Funding for Sanctuary Cities", summary: "Cuts funds to non-compliant cities", bill_status: "No bill yet", bill_link: null, court_challenges: "Lawsuit filed—CA, 4/3/25", court_link: "https://x.com/search?q=California%20lawsuit%20EO%2014158", risk_level: 8, impact_level: "High", last_updated: "4/4/25" },
    { eo: "14159", title: "Reforming Federal Permitting for Infrastructure", summary: "Speeds up project approvals", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 4, impact_level: "Medium", last_updated: "1/21/25" },
    { eo: "14160", title: "Banning Transgender Individuals from Military Service", summary: "Reinstates 2019 ban", bill_status: "No bill yet", bill_link: null, court_challenges: "Negative ruling, 4/5/25", court_link: "https://x.com/search?q=ACLU%20lawsuit%20EO%2014160", risk_level: 9, impact_level: "Medium", last_updated: "4/7/25" },
    { eo: "14161", title: "Eliminating Critical Race Theory from Federal Training", summary: "Bans CRT in gov programs", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 4, impact_level: "Medium", last_updated: "1/21/25" },
    { eo: "14162", title: "Strengthening Border Wall Construction", summary: "Funds wall via DoD budget", bill_status: "No bill yet", bill_link: null, court_challenges: "Lawsuit filed—Tribal Nations", court_link: "https://x.com/search?q=Tribal%20Nations%20lawsuit%20EO%2014162", risk_level: 9, impact_level: "High", last_updated: "2/10/25" },
    { eo: "14163", title: "Expanding Tariffs on Chinese Imports", summary: "Raises tariffs to 25% on tech", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 5, impact_level: "High", last_updated: "2/15/25" },
    { eo: "14164", title: "Deregulating Federal Healthcare Programs", summary: "Cuts ACA rules, boosts private plans", bill_status: "No bill yet", bill_link: null, court_challenges: "Lawsuit threatened—AARP", court_link: "https://x.com/search?q=AARP%20lawsuit%20EO%2014164", risk_level: 8, impact_level: "High", last_updated: "2/20/25" },
    { eo: "14165", title: "Prohibiting Federal Funds for Abortion Services", summary: "Defunds Planned Parenthood", bill_status: "No bill yet", bill_link: null, court_challenges: "Lawsuit filed—PPFA", court_link: "https://x.com/search?q=Planned%20Parenthood%20lawsuit%20EO%2014165", risk_level: 8, impact_level: "Medium", last_updated: "3/1/25" },
    { eo: "14166", title: "Restoring Law Enforcement Funding", summary: "Boosts ICE, police grants", bill_status: "Optional—exec power", bill_link: null, court_challenges: "None", court_link: null, risk_level: 4, impact_level: "Medium", last_updated: "2/25/25" },
    { eo: "14167", title: "National School Choice Expansion", summary: "Funds private school vouchers nationwide", bill_status: "Intent declared by Rep. Z, 4/2/25", bill_link: null, court_challenges: "None", court_link: null, risk_level: 5, impact_level: "High", last_updated: "4/4/25" },
    { eo: "14168", title: "Reforming Federal Prison System", summary: "Reduces federal prison costs via private contracts", bill_status: "No bill yet", bill_link: null, court_challenges: "None", court_link: null, risk_level: 5, impact_level: "Medium", last_updated: "4/1/25" }
];

const eosCount = 22;